---
name: "Format"

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: main

jobs:
  lint:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Check code formatting with black
        run: black --check django_atlas_search tests

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 django_atlas_search tests --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 django_atlas_search tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
