---
name: "PyPI Release"

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

jobs:
  pypi-publish:
    name: PyPI Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/django-atlas-search
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build Distribution
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_AI_TOKEN }}
